package com.ia.patientservice.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import java.util.UUID;

// mark as entity class
@Entity

public class Patient {
    @Id
    @GeneratedValue (strategy = GenerationType.AUTO)
    private UUID id; // this makes the id autogenerated by the database


}
