### This updates an existing patient in the database
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174011
Content-Type: application/json

{
  "name": "John Doe",
  "email": "testing@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1995-09-09",
  "registrationDate": "2023-03-04"
}

###